server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定rabbit Mq的服务信息
        defaultRabbit: #表示定义的名称，用于binging整合
          type: rabbit #消息组件类型
          enviroment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理的
          output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit